apiVersion: v1
kind: Secret
metadata:
  name: portfolio-repository
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:mhw29/portfolio.git
  sshPrivateKey: cat /Users//matthewwilliamson/.ssh/id_rsa