apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2023-12-19T12:14:14Z"
  labels:
    kubernetes.io/metadata.name: ingress
  name: ingress
  resourceVersion: "2125396"
  uid: 5950c108-8015-4d0f-8f8e-b557955b3a88
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
